<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\sisstudioWA.BD\sisstudioWA.BD.csproj" />
    <ProjectReference Include="..\sisstudioWA.Shared\sisstudioWA.Shared.csproj" />
  </ItemGroup>

</Project>
